site_name: Orsino
site_url: https://jweissman.github.io/orsino/

theme:
  name: material
  palette:
  - scheme: default
    media: "(prefers-color-scheme: light)"
  - scheme: slate
    media: "(prefers-color-scheme: dark)"

  # custom_dir: 'cinder'
# extra_css:
#   - css/dark.css

nav:
  - Home: index.md
  - DMG: dmg.md
  - PHB: phb.md
  - MM: mm.md
